eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.server.ipAddress}:${server.port}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eureka
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet.allow: true
  application:
    name: product
server:
  port: 9991
mybatis:
  type-aliases-package: com.zhli13.server.pojo
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.zhli13.utils.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params:
    count: countSql
girl:
  name: "zhli13"
  age: "28"
